### ISSUE TITLE
The required goods, coins, supplies, FPs and Orichalcum are not matching the game

### ISSUE THREAD

**Issue by WindowsSystemAdmin** [WindowsSystemAdmin/research#2]
The goods required for the specific tech is not updating when checked.

**Comment by WindowsSystemAdmin** [comment]
Working on the issue right now.

**Comment by WindowsSystemAdmin** [comment]
Unsure about what the correct number of the resources are.. I have two different resources telling me different things.

**Comment by WindowsSystemAdmin** [comment]
There's a partial fix... Waiting to see what happens when I add the new age..

**Comment by SystemsUser** [comment]
Not quite yet.

**Comment by SystemsUser** [comment]
Alright.. 600 FPs removed is reviewed. Closing and marked as fixed!
